### ISSUE TITLE
Use of inline definitions

### ISSUE THREAD

**Issue by mbaudis** [ga4gh-schemablocks/sb-duo#1]
The current documentation parser doesn't properly handle inline `definitions` objects. This could be added; but the current concept had more been to have flat `properties` and reference external definitions (to keep the "reusable blocks" concept).

Opinions, @theisuru, @mcourtot ?

**Comment by theisuru** [comment]
@mbaudis I completely agree with you. I put definitions block so that its easier to read in one document. But as you mentioned we should make them as small as possible. I will extract DataUseModifier into a separate block.
